### ISSUE TITLE
Error when overriding URL is set but HttpClient receives relative URLs

### ISSUE THREAD

**Issue by PaulDMooney** [hapinessjs/ng-universal-transfer-http#17]
The scenario:
On the server side we're using absolute URLs to make API calls through the HttpClient
On the client side we're using relative URLs to make these API calls, since the web server hosting the app also proxies the API calls to the appropriate backend services.

Since the relative URLs received by the TransferHttpCacheInterceptor do not have a protocol portion to them, an error gets thrown in the browser:  

> Uncaught TypeError: Cannot read property 'split' of undefined

This seems to originate from this line here: https://github.com/hapinessjs/ng-universal-transfer-http/blob/1e8459656d580adb921eff5f59c8a94ec05d11f4/projects/ng-universal-transfer-http/src/lib/shared/services/transfer-http-cache-interceptor/transfer-http-cache.interceptor.ts#L493  which would not have an array index of 1 if the incoming url has no protocol portion to split '://' on.

**Comment by njl07** [comment]
@PaulDMooney thanks to use this library.

First, if you want to have caching, you must use the **same** url in `server` and `client` sides.
If the url changes, cache will not be applied because the request is different.

Second, when you use the option to set the header it's to override the url of the `server` side with the url of the `client` side like cache will be ok in both side.

URL in `client` must be type of `http(s)://my_server.com` because you path through the browser and you must contact your server.

We use it in our production and all is working fine.
