### ISSUE TITLE
'Request missing in server state data' error when making new request from client

### ISSUE THREAD

**Issue by PaulDMooney** [hapinessjs/ng-universal-transfer-http#18]
Scenario:
1. The page has been rendered on the server and loads up in the browser.
1. The user takes a new action which triggers an http request to get more data, purely from the client side.
1. An error gets thrown `Request missing in server state data`

Expected outcome: New HttpClient requests from the browser, which had not previously been triggered from SSR, should not cause an error.

**Comment by njl07** [comment]
@PaulDMooney the error is triggered because you have no **state** between `server` and `client`.

**All requests from the browser must be triggered in server too**.

Check the [tutorial](https://github.com/hapinessjs/ng-universal-transfer-http/blob/master/projects/ng-universal-transfer-http/README.md) to configure correctly your project.

Thanks.

**Comment by ThePatzen** [comment]
Hi!

I have the same issue!

@njl07 If i use the universal TransferHttpCacheModule for of http GET requests works fine!
If i switch to this Module it breaks my app. 

Please tell me if i'm wrong: 
When i use the angular router to switch to a different component...
Then a http request is called from the client side. So this request will never be called "also on the server side".

Best Regards!

**Comment by njl07** [comment]
Hi @ThePatzen and thanks to use this library.

I don't know what are you doing exactly but in your comment I can see something wrong and a misunderstood how the module is working.

This module caches server request to not be executed in client side and the reverse with client cache to not be executed in serve side.

This module is used with Angular Universal module provide by `Hapiness framework`.

Follow the [tutorial](https://github.com/hapinessjs/ng-universal-transfer-http/blob/master/projects/ng-universal-transfer-http/README.md) and all will work fine.

Don't hesitate if needed.

**Comment by rakeshkr8880** [comment]
**Request missing in server state data** 
Uncaught Error: Request missing in server state data
    at e.project (hapiness-ng-universal-transfer-http.js.pre-build-optimizer.js:203)
    at e._tryNext (mergeMap.js.pre-build-optimizer.js:61)
    at e._next (mergeMap.js.pre-build-optimizer.js:51)
    at e.next (Subscriber.js.pre-build-optimizer.js:54)
    at e._complete (defaultIfEmpty.js.pre-build-optimizer.js:33)
    at e.complete (Subscriber.js.pre-build-optimizer.js:66)
    at e._complete (Subscriber.js.pre-build-optimizer.js:84)
    at e.complete (Subscriber.js.pre-build-optimizer.js:66)
    at e._complete (mergeMap.js.pre-build-optimizer.js:79)
    at e.complete (Subscriber.js.pre-build-optimizer.js:66)

Getting this issue with hapinessjs after implementing hapinessjs as described.

**Comment by njl07** [comment]
It means that your `request` doesn’t exist in `SSR` so when you switch in `client` side, the library can’t retrieve it

**Comment by rakeshkr8880** [comment]
Hi @njl07, 

Really thank you for your prompt response. I tried calling same request from ssr but had no luck.

**Comment by njl07** [comment]
Check our tutorial to know exactly how to implement it with SSR and to have it working in dev too because we have no issue in our projects delivered in production

**Comment by njl07** [comment]
@PaulDMooney @ThePatzen @rakeshkr8880 I've found your problem and sorry for the delay.

I've never been in this situation before because our applications are doing call before each `route` in `guards` so interceptor was always intialized.

But, if an application is rendered in `SSR` with a component not doing a call and after you move to another one doing a call, `interceptor` is initialized with a bad value for `cache flag` so data are missing in server state.

Now it's fixed with the latest version of `Angular` so sorry for the delay and don't understand your problem.

Next time, try to explain the way to reproduce it and it can be easier to fix it.

Thanks again to say to me this issue.

**Comment by njl07** [comment]
https://github.com/hapinessjs/ng-universal-transfer-http/commit/522e314a30c6adbbcfa21002c8cef136504b3023
