### ISSUE TITLE
Wrong id for server state data

### ISSUE THREAD

**Issue by tibinthomas** [hapinessjs/ng-universal-transfer-http#24]
For an HTTP call, I get this error after client loading: **Wrong id for server state data**.
In server there is no such error.

**Comment by njl07** [comment]
This error is caused by a desynchronisation between `server` and `client` and the requests send by the `client` are not in the same order than in the `server` so the unique identifier of the last request can be found.

You have a problem in your angular calls implementation.

Check the [tutorial](https://github.com/hapinessjs/ng-universal-example) and normally all will be fine because we have no problem in all applications in production

**Comment by tibinthomas** [comment]
OK.  I accept. But I can't find the reason behind the desync in API calls. Please help

**Comment by tibinthomas** [comment]
Temporarily I solved the issue in my project by calling a dummy API call as the last one. But I believe we can have a better solution.

**Comment by njl07** [comment]
Have you parallel calls ? Even it’s the case the library manages them. I think you have not the same number of calls in front and server. Go in source code of the library and logs the array of ids and you will see if it’s the same
